# Starter pipeline
trigger:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'armsp11'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azure-dev'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: 'https://github.com/shubhammicrosoft1/azure-quickstart-templates/blob/master/docker-simple-on-ubuntu/azuredeploy.json'
    csmParametersFile: 'https://github.com/shubhammicrosoft1/azure-quickstart-templates/blob/master/docker-simple-on-ubuntu/azuredeploy.parameters.json'
    deploymentMode: 'Complete'
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
