# Starter pipeline
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'armsp11'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azure-dev'
    location: 'West US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/shubhammicrosoft1/azure-quickstart-templates/blob/master/docker-simple-on-ubuntu/azuredeploy.json'
    csmParametersFileLink: 'https://github.com/shubhammicrosoft1/azure-quickstart-templates/blob/master/docker-simple-on-ubuntu/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'docker vm'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
